### ISSUE TITLE
Is it possible to use pre-ranked gene lists in EGSEA?

### ISSUE THREAD

**Issue by TiaGlia** [malhamdoosh/EGSEA#20]
Hi,

I don't know if this is the proper channel to make this question, but I was wondering if it is possible to use a pre-ranked list in EGSEA or we need a countmatrix or voom object to start with? I have some colleagues who work on single-cell data, and the structure is a bit different. It is not possible to get a countmtx, and using voom doesn't make sense since Seurat works differently than bulk-RNAseq and microarray (EdgeR, limma, voom).
So would it be possible to get a list of differentially expressed genes (findAllmarkers function from Seurat) and input that pre-ranked list in EGSEA, such as it is possible using GSEA?

Thanks in advance!
Tiago

**Comment by malhamdoosh** [comment]
No this is not possible. EGSEA is designed to extend limma-voom pipeline.
